<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>reCAPTCHA</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="https://www.google.com/recaptcha/api.js"></script>
<style type="text/css">
.error { color:#ff0000; }
</style>
</head>
<body>

<script>
$(document).ready(function() 
{
    $("#submit").on('click', function() 
    {
        var form_data = {
        recaptcha: $('.g-recaptcha-response').val()
        };
        $.ajax({
        type: "POST",
        url: 'send.php',
        data: form_data,
        success: function(response)
        {    
            if (response == 'error_captcha') {
                $('.msg').html('<p class="error">Zaznacz, że nie jesteś robotem.</p>');
            } else {
                $('.msg').html('<p>Ok, nie jesteś robotem :) Wiadomość została wysłana.</p>');
            }
        }
        });
        return false;
    });
});
</script>

<form action="" method="post">
<div class="g-recaptcha" data-sitekey="TWÓJ SITE KEY"></div>
<p><a id="submit" href="#">Wyślij formularz</a></p>
</form>
<div class="msg"></div>

</body>